Fixed the errors in app.py
Vuka951/tutorial-code pull request #87
Opened 2023-07-09 13:18 UTC by abhibansal60

2023-07-20 09:56 UTC, Greko2017 approved these changes

2023-07-26 22:13 UTC, astyles97 requested changes
There is a syntax error : "_SyntaxError: keyword argument repeated: client_kwargs_".
It can be fixed by:     
`client_kwargs={"scope": "openid profile email", "scope": "email profile"}
`

2023-07-26 22:44 UTC, astyles97 approved these changes
Works

2023-07-28 01:44 UTC, astyles97 approved these changes

2023-08-15 09:59 UTC, shaarful approved these changes

2024-01-04 21:59 UTC, Vuka951 approved these changes

2024-01-04 22:00 UTC, merged